---
title: "Shiny Survey Results"
author: "Shiny Survey Team"
date: "11/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Opinions about fruit


```{r getdatasetup, include=FALSE, echo=FALSE}
#install.packages("ggplot2")
library(ggplot2)
library(googledrive)
library(googlesheets4)



#setwd("/home/student17/Shinyrep") 

# The following command works when running in the console, but not yet from markdown, because you need to log in by hand. Probably use drive_auth(email = "shiny.h4ss@gmail.com") later?
#drive_download("~/response.csv", overwrite = TRUE)
#df <- read.csv(file = 'response.csv')

gs4_auth(email = "shiny.h4ss@gmail.com")

df<- read_sheet("https://docs.google.com/spreadsheets/d/1v0Dhyxozn3qz6WW54ZS03_qqO12g1Nzf5gXLBhgSmP0/edit#gid=619522926")

#Delete blanks in Variable names
names(df) <-gsub(" ", "", names(df))
#Delete special characters
names(df) <-gsub("-", "", names(df))
  
```


This survey was completed by `r nrow(df)` participants.


```{r question1, echo=FALSE}

# Colors
fruitcolors=c("#86D76E", "#E3F25A", "#913838","#E8A22B")

p1 <- ggplot(df, aes(x = FavoritefruitSC, fill = FavoritefruitSC)) +
  geom_bar()+
  theme_bw()+
  scale_fill_manual(values= fruitcolors)+
  theme(legend.position = "none")+ 
  xlab("Fruit")+
  ylab("Number of Participants")+
  labs(title = "What is your favourite fruit?")

p1

```
