---
title: "Shiny Survey Results"
author: "Shiny Survey Team"
date: "11/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Opinions about fruit


```{r getdatasetup, include=FALSE, echo=FALSE}
#install.packages("ggplot2")
library(ggplot2)
library(googledrive)
library(googlesheets4)
library(wordcloud)
library(tm)
library(tidytext)
library(reshape2)
library(dplyr)


#################################

# Change 
#setwd("./shinyrep") 

gs4_auth(cache = ".secrets", email="shiny.h4ss@gmail.com")

df<- read_sheet("https://docs.google.com/spreadsheets/d/1v0Dhyxozn3qz6WW54ZS03_qqO12g1Nzf5gXLBhgSmP0/edit#gid=619522926")

#Delete blanks in Variable names
names(df) <-gsub(" ", "", names(df))
#Delete special characters
names(df) <-gsub("-", "", names(df))
  
```


This survey was completed by `r nrow(df)` participants.


```{r question1, echo=FALSE}

# Colors
fruitcolors=c("#86D76E", "#E3F25A", "#913838","#E8A22B")

p1 <- ggplot(df, aes(x = FavoritefruitSC, fill = FavoritefruitSC)) +
  geom_bar()+
  theme_bw()+
  scale_fill_manual(values= fruitcolors)+
  theme(legend.position = "none")+ 
  xlab("Fruit")+
  ylab("Number of Participants")+
  labs(title = "What is your favourite fruit?")

p1

```


## Quetsion 2

```{r question2, echo=FALSE}

# Subset including the relevant variables
sub <- df[,2:5]
sub$id <- row.names(sub)

# Reshape data
molten <- reshape2::melt(sub, id.vars = c("id"))
molten$variable <- factor(molten$variable)

# Plot
p2 <- ggplot(molten, aes(x = variable, y = value, fill = variable)) +
  geom_col()+
  theme_bw()+
  scale_fill_manual(values= fruitcolors)+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c("FavoritefruitsMCApple" = "Apple", "FavoritefruitsMCBanana" = "Banana", "FavoritefruitsMCCherry" = "Cherry", "FavoritefruitsMCOrange"= "Orange"))+
  xlab("Fruit")+
  ylab("Number of Votes")+
  labs(title = "What is your favourite fruit?")

p2

```

## Quetsion 3

```{r question3, echo=FALSE}

p3<- ggplot(df, aes(x="", y=FavoritefruitDD, fill=FavoritefruitDD))+
  geom_bar(width = 1, stat = "identity")+
  coord_polar("y", start=0)+
  theme_bw()+
  theme(axis.title.x=element_blank(),
        axis.title.y=element_blank(),
          panel.grid=element_blank(),
        panel.border = element_blank()) +
  scale_fill_manual(name = "Fruit", values= fruitcolors)+
  labs(title = "What is your favourite fruit?")
p3


```

## Question 4

```{r question4, echo=FALSE}


p4 <- ggplot(df, aes(y = Ratingofbananas)) +
  geom_boxplot(fill= fruitcolors[2])+ 
  coord_flip()+
  theme_bw()+
  scale_x_discrete()+
  scale_y_continuous(labels=c("1" = "Totally disagree", "2" = "2", "3" = "3", "4"= "4", "5"= "Totally Agree"))+
  ylab("Banana Rating")+
  labs(title = "I like Bananas")

p4

```


## Question 5

```{r question5, echo=FALSE}

# Subset including the relevant variables
sub <- df[,8:11]
sub$id <- row.names(sub)

# Reshape data
molten <- reshape2::melt(sub, id.vars = c("id"))
molten$variable <- factor(molten$variable, 
                          levels = c("Ratingofstaff","Ratingofcleanliness","Ratingofspa","Ratingoffood"),
labels = c("Staff", "Cleanliness", "Spa", "Food"))



p5 <- ggplot(molten, aes(factor(value)))+
  geom_bar()+
  facet_grid( ~ variable)+
  theme_bw()+
  labs(title = "Hotel ratings")+
  xlab("Ratings")+
  scale_x_discrete(labels=c("1" = "Very satisfied", 
                            "2" = "Satisfied",
                            "3" = "Neither",
                            "4" = "Dissatisfied", 
                            "5"="Very dissatisfied"))+
  theme(axis.text.x = element_text(size=10, angle=90))+
  ylab("Count")

p5


```


## Question 6
```{r question6, echo=FALSE}

# Clean data
df$Opinion_clean<-gsub("[[:punct:]]", "", df$Opinion)


# Make data frame with words in one column and count in the other colum
survey_words <- df %>% 
  select(Opinion_clean) %>% unnest_tokens(word, Opinion_clean)

wordscount <- survey_words %>% count(word, sort=TRUE)


set.seed(123)
wordcloud(words = wordscount$word, freq = wordscount$n, min.freq = 1)

```






